name: green_pen
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.1
  connectivity_plus: ^2.3.3
  #sms_autofill: ^2.2.0
  pin_code_fields: ^7.3.0
  font_awesome_flutter: ^10.1.0
  smooth_page_indicator: ^1.0.0+2
  shared_preferences:
  stop_watch_timer: ^1.3.1
  dio: ^4.0.6
  device_info_plus: ^3.2.3
  dotted_line: ^3.1.0
  carousel_slider: ^4.0.0
  custom_radio_grouped_button: ^2.1.2
  intl: ^0.17.0
  image_picker: ^0.8.4+1
  flutter_native_image: ^0.0.6+1
  scrollable_positioned_list: ^0.2.3
  image_cropper: ^2.0.0
  flutter_widget_from_html_core: ^0.8.5+1
  syncfusion_flutter_charts: ^20.1.51
  flutter_launcher_icons:
  alt_sms_autofill: ^1.0.0
  permission_handler: ^9.2.0
  razorpay_flutter: ^1.3.0
  pull_to_refresh: ^2.0.0
  showcaseview: ^1.1.5
  new_version: ^0.3.0
  firebase_messaging: ^11.4.2
  flutter_local_notifications: ^9.4.0
  firebase_core: ^1.18.0
#  progress_dialog_null_safe: ^1.0.7
  flutter_easyloading: ^3.0.5
  percent_indicator: ^4.0.0

flutter_icons:
  image_path: "assets/images/app_logo.png"
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/uil_signout.png
     - assets/png_file/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Black.ttf
          weight: 900
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Thin.ttf
          weight: 100
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
